### PR TITLE
Integration Spec & `N+1` Fix

### PR DESCRIPTION
**Pull request by PraisesPJMT**
# Inkling Blog App | Integration Spec & `N+1` Fix #8
## Project Description
Create integration tests for all of the views used in the project and secure the app from `N+1` problems.
## Project Team
- @Moathal 
- @PraisesPJMT 
### n+1
- Made sure that the `N+1` problem is solved when fetching all posts and their comments for a user. 
### Integration specs
-  Used Capybara to write integration tests for each view in the project. Tests were written for the following
  - `User` `#index` page
  - `User` `#show` page
  - User `Post` `#index` page
  - `Post` `#show` page

Happy Reviewing!!!!!

### CODE REVIEW

**Review by mukhammadrizooff — CHANGES_REQUESTED** [review]
Hi @PraisesPJMT, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- No linter errors ✔️ 
- Good implmentations ✔️ 


## Required Changes ♻️
- [ ] [REQUIRED] Good job so far 👍 I really appreciate what you did, but you should have `4` "integration specs for views" files. So first file `User` **index page**, second file `User` **show page**, third file `User` **post index page**, last one `User` **post show page** but you wrote the `index` and `show` parts together in the `User` and `Post` spec files, therefore you have a total of 2 files. Please write `index` and `show` parts for `User and Post` seperately then your work will be clean 🙏

image

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PraisesPJMT** [comment]
## Review Feedback
Thanks so much @mukhammadrizooff  for the feedback
## Required Changes
Based on the review, we made the following recommended changes:
- Separate tests for `#index` & `#show` pages of `Users`
- Separate tests for `#index` & `#show` pages of `Posts`


Happy Reviewing!!

**Review by HAMMAS-SALEEM — APPROVED** [review]
# Status: Approved :green_circle: :1st_place_medal: :100:
success
### Hey @PraisesPJMT, @Moathal 👋

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Linters
✔️ Following Requirements

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PraisesPJMT** [comment]
Thanks @mukhammadrizooff  and @HAMMAS-SALEEM for the feedback!

**Comment by HAMMAS-SALEEM** [comment]
Hey @PraisesPJMT, @Moathal

You guys have done a great job. Keep doing great things 😊
Happy Coding 👍

**Pull request merged**
